### ISSUE TITLE
Abnormal exit in Command-line window

### ISSUE THREAD

**Issue by bohrshaw** [wellle/targets.vim#101]
Bug: `vi'` or `vib` exits the Command-line window.

**Comment by wellle** [comment]
Thanks for the bug report, can reproduce. I will try to look into this in the next days.

**Comment by wellle** [comment]
I used <kbd>C-\\</kbd><kbd>C-N</kbd> before to switch from visual to normal mode. Apparently this also closes the command-line window. It's fixed in #102. Thanks again!
