### ISSUE TITLE
Issues when 'virtualedit' has onemore

### ISSUE THREAD

**Issue by grota** [wellle/targets.vim#103]
I have in my vimrc `set virtualedit+=onemore`. This seems to create issues (the operated-on text is larger than expected).

**Comment by wellle** [comment]
I just added that setting to my vimrc, but failed to find any issue after doing some quick checks. Could you show me an example of an unexpected operation?

**Comment by grota** [comment]
I made a gif showing it, let me know if it's too fast or if you want it shown in another way.
![onemore](https://cloud.githubusercontent.com/assets/403432/6318178/d4d8f58c-ba7a-11e4-9254-70b5854a51a5.gif)

**Comment by wellle** [comment]
I see. Will fix.

**Comment by wellle** [comment]
Some internals were confused by that setting. It is now temporarily set to default on invocation and reset to the user setting when done. Fixed in #104. Thanks :+1:

**Comment by grota** [comment]
thank you :)
