### ISSUE TITLE
Argument Text Object: Next/Last Count Warning Message

### ISSUE THREAD

**Issue by orbisvicis** [wellle/targets.vim#108]
```
v2ana
               +
function(a, f2(1, 2, 3, 4, 5, 6), b)
                   +++
E486: Pattern not found: N
```

**Comment by orbisvicis** [comment]
Also note this selection isn't possible:
```
               +
function(a, f2(1, 2, 3, 4, 5, 6), b)
                                +++
```
For that, see my proposal #105.

**Comment by wellle** [comment]
I don't get that error message. Maybe you pressed `n` and your last search pattern `N` wasn't found? I tried it with your Vim version 7.4.273 and it worked as expected. Please try again and reopen if you see it again. In that case, what version of targets.vim are you using?

To select `, b`, type `v6ana`

**Comment by orbisvicis** [comment]
Yes, can't replicate this either.
