### ISSUE TITLE
Separator Text Object: Should Support Count and Ignore Quote/Pair Text Objects

### ISSUE THREAD

**Issue by orbisvicis** [wellle/targets.vim#111]
Expected:
```
v2in.
       +
"a" . "b" . "c" . "dd . ee . ff" . "c" . "b" . "a"
                 ++++++++++++++++
```

With behaviour similar to that of pairs text objects:

```
v3in.
       +
"a" . "b" . "c" . "dd . ee . ff" . "c" . "b" . "a"
                 +++++
```

Be extension, [count] would break out of separator objects nested in quotes or pairs:
```
v2i.
                        +
"a" . "b" . "c" . "dd . ee . ff" . "c" . "b" . "a"
                 ++++++++++++++++
```

**Comment by wellle** [comment]
Same issue as described here: https://github.com/wellle/targets.vim/issues/107#issuecomment-89262833
```
line   | "a" . "b" . "c" . "dd . ee . ff" . "c" . "b" . "a"
quotes | " "   " "   " "   "            "   " "   " "   " "
cont A |  1     3     5     777777777777     9     A     C
cont B |    222   444   666              888   000   BBB
```
How to chose contents? (Lets continue that discussion in #107)

And in general this looks like a problem to be solved with `"` objects, not `.` objects. It's ok that not all text objects can be used to select each target. Each text object should specialize on a real use case. `vi.` is meant to select between dots. I'm not convinced that nesting and handling quotes and pairs are needed for this. This is supposed to be a simple text objects. (Argument text objects are a bit more sophisticated and might benefit from special handling of real world problems)

And looking at your contrived example this doesn't seem to be a real issue you have. Please show me an example where this would actually be a useful addition.

**Comment by orbisvicis** [comment]
I agree, this isn't a high priority issue.
