### ISSUE TITLE
let g:targets_nlNL = 'nN  ' not working

### ISSUE THREAD

**Issue by sunaku** [wellle/targets.vim#113]
Forward searching with `vin)` works correctly, but backward searching with `viN)` does not.

I'm using version 567a293e5004889d6c02ffe9fd44c5fb3a760a13 of this plugin.  Thanks! :sweat_smile:

**Comment by wellle** [comment]
I will have a look. :+1:

**Comment by wellle** [comment]
Fixed in https://github.com/wellle/targets.vim/pull/115, thanks :+1:

**Comment by sunaku** [comment]
Fix confirmed, thanks! :bow:
