### ISSUE TITLE
Visual Mapping Question/Issue

### ISSUE THREAD

**Issue by lag13** [wellle/targets.vim#117]
First off, I want to say thanks for writing this plugin! It has some nifty new text objects (arguments stick out in my mind) and I like the altered behavior for some existing objects. I have a sort of issue but I suppose it's more of a question. Sorry if this is the wrong place ask.

Why did you use expression mappings for the visual mode mappings? I ask this because when I first installed this plugin I was running vim version 7.3 and to my dismay visual mappings wouldn't work! Looking into it, I found out that using getchar() inside of an expression mapping didn't really work well until patch 7.3.338. Since I still wanted to use this plugin, I forked your repository and made a fix involving "manually" creating all the visual mappings: https://github.com/lag13/targets.vim/commit/224f5050ec2e50df5cfc106c58c6f9597f5c9eff

So why did you use expression mappings? Was it to improve startup time?

**Comment by wellle** [comment]
@lag13: Yes, I moved to expression mappings in #90 to improve startup time #77.

Out of curiosity, can you run this like five times with `welle/targets.vim` and five times with `lag13/targets.vim` and share the results here?
```sh
vim --startuptime time.vim +q && grep targets time.vim && rm time.vim
```
I'd like to know how big the difference is nowadays. Thanks.

**Comment by lag13** [comment]
@wellle: Of course! I ran it three times for both your original plugin and my fork:

Your current plugin (with expression mappings):

    1. 048.747  021.295  021.295
    2. 048.741  021.177  021.177
    3. 049.719  021.246  021.246

My fork (no expression mappings):

    1. 069.800  042.511  042.511
    2. 067.237  039.418  039.418
    3. 070.970  041.262  041.262

So about twice as slow, which makes sense.

**Comment by wellle** [comment]
@lag13: Thanks :+1:

How do you feel about about using expression mappings for new Vim versions and explicit mappings for older versions? That way it's fast for me and still works for you.

It looks like you're quite comfortable with Vimscript. Do you want to give it a try and open a pull request? Thanks.

**Comment by lag13** [comment]
@wellle: Sure! I'll try to get that done by the end of the weekend.

Do you mind if I also throw in support for repeating with the '.' command for earlier versions? https://github.com/lag13/targets.vim/commit/a7f76c2f68afbfd0ce3d5008778a9d3dd6b4ddca

I feel like if we don't have the '.' command available then this plugin becomes a lot less useful. This would require Tim Pope's repeat.vim, but I think that's to be expected.

**Comment by wellle** [comment]
Sure, go ahead. I believe a proper integration of repeat.vim wouldn't break targets.vim for users who don't have repeat.vim installed. So that shouldn't lead to problems for anyone.
