### ISSUE TITLE
Add support for angle brackets

### ISSUE THREAD

**Issue by baabelfish** [wellle/targets.vim#120]
I use a lot of C++ templates and it would benefit me a lot. Currently when adding those brackets into the bracketlists (targets_argOpening, targets_argClosing) it doesn't work with the first and last argument.

**Comment by wellle** [comment]
Setting this works for me:
```vim
let g:targets_argOpening = '[({<]'
let g:targets_argClosing = '[>})]'
```
Please show me an example:
- buffer content
- cursor position
- the command you type
- what you get
- what you expect

**Comment by baabelfish** [comment]
Very odd, they seem to be working now... It might have been some other plugin interfering.

**Comment by wellle** [comment]
Glad it works now :+1:
