### ISSUE TITLE
Respecting vim's 'quoteescape' option

### ISSUE THREAD

**Issue by lag13** [wellle/targets.vim#121]
Hello again! I was programming the other day and tried to change inside a double quoted string which had escaped double quotes in it. So it might have looked something like this:

```vim
let var = "I like to say \"hello world\""
```

After doing ```ci"``` I expected the whole string to be deleted but instead, it only deleted from the "I" to the "\" character. So the ```i"``` text object did not ignore the escaped double quotes. I seemed to remember vanilla vim's ```i"``` object ignoring escaped quotes so I looked into it and found the [```'quoteescape'``` option](http://vimdoc.sourceforge.net/htmldoc/options.html#'quoteescape').

Do you think you'd like to add support to respect this setting? If so then I could create a PR: https://github.com/wellle/targets.vim/compare/master...lag13:respect-qe-option?expand=1. Let me know!

**Comment by wellle** [comment]
Hi @lag13! Yes I wanted to add support for this for a while. Please open the PR! Your implementation looks good. Why do we need the `copy()` call?

**Comment by lag13** [comment]
Haha woops. Yep, we do not need that ```copy()``` call. Just made the PR!
