### ISSUE TITLE
Consider a seekmode option

### ISSUE THREAD

**Issue by chochkov** [wellle/targets.vim#127]
I've often been frustrated when mistyping something like `di(` and `targets` takes me to a remote place in the file where the next occurrence of a `(..)` is. This is in most cases not what I want (what i do want in those cases is to _bloody stop typing the wrong thing!!_). Anyway, if we want to seek in multiline we could always use `din(`.

After discussing with @wellle, he suggested having an option to specify `targets_seekmode` as `line` or `multiline` to manage the seek behaviour. I think that would be great!

**Comment by wellle** [comment]
I just checked the related code, restricting seeking to the current line should be pretty easy to implement. Possible seek modes we might consider for the future:
- don't seek at all
- seek current line (proposed)
- seek currently visible lines
- seek full buffer (current, default)

And we could even have that independently for both forward and backward seeking. So you could set it up to only seek backwards in the current line and forward only in visible lines.

For the record: The current seeking works like this (in order):
- try text object around cursor
- seek forward in current line
- seek backward in current line
- seek forward until last line of buffer
- seek backward until first line of buffer

If there is demand we could also make this adjustable.

**Comment by chochkov** [comment]
Sounds great @wellle. I suppose the seek line option will also first try text object around, then forwards, then backwards. :+1:

**Comment by wellle** [comment]
Yes.
