### ISSUE TITLE
b to match all types of brackets

### ISSUE THREAD

**Issue by balta2ar** [wellle/targets.vim#131]
How do I configure targets so that `b` triggers the nearest bracket of any type?
I want something like this:

``` vim
let g:targets_pairs = '()b {}b []b <>b'
```

But this way it does not work.
Thanks!

**Comment by balta2ar** [comment]
If I get the docs right, `t` is what I want. Judging from the examples, it matches any type of brace. Am I right? If I am, however, it's not working. Is this something in my configuration? If so, how do I track that?

**Comment by khalidchawtany** [comment]
I don't think targets has any such a functionality to trigger multiple text objects using the same key. However, there is a plugin "[vim-textobj-anyblock](rhysd/vim-textobj-anyblock
)" that does a pretty good job.

If targets could do this, I would be very happy to remove yet another plugin from my vimrc :)

**Comment by wellle** [comment]
@khalidchawtany is right. That functionality is currently not available. `t` is for working on tags like `<a>b</a>`.

But this is a good idea. I was already considering adding a similar feature to target any quote with `aq`, combining `a'`, a`"` and ``a` ``. Similarly it should be possible to map `ab` to combine `a(`, `a[`, `a{` and `a<`. I'll see what I can come up with, but it's probably not going to happen soon.

**Comment by balta2ar** [comment]
Thanks, @khalidchawtany, it's working! For those who might stumble on this issue in the future, here is a configuration that does what I want:

``` vim
let g:targets_pairs = '() {} [] <>'
let g:textobj#anyblock#blocks = ['(', '{', '[', '<']
```
