### ISSUE TITLE
Selecting text _between_ different pairs – is it nomal?

### ISSUE THREAD

**Issue by for-coursera** [wellle/targets.vim#137]
Let's say I have the following situation:

![before](http://i.imgur.com/yzZ6N2G.png)

As it may be seem, the cursor is on the closing quote. Then I press `ci'`, and the result is like that:

![after](http://i.imgur.com/mYYwLNN.png)

While I'd expect it should be like that:

![instead](http://i.imgur.com/xtE6RwL.png)

Thus, my question, is it a bug? And if not, then how to achieve the desired behaviour?

Thanks.

**Comment by wellle** [comment]
@for-coursera: Yes I noticed the same recently and started reimplementing the quote text object handling completely to be more clever about selecting quoted objects.

You can find the new implementation on branch [`improve-quotes`](https://github.com/wellle/targets.vim/compare/improve-quotes). I would appreciate if you could give that a try and let me know if that works for you.

Please note that this makes it impossible to select the pseudo quotes like `' non quoted test '` in your example. I've been using this for a while and for me that hasn't been an issue so far.

**Comment by for-coursera** [comment]
Seems to be working as it should (commands like `dil'`, too). Thanks.

**Comment by wellle** [comment]
Thanks for checking. I'll try to get more opinions on this before I move forward with it.

**Comment by wilywampa** [comment]
@wellle I noticed that if the cursor is on a quote at the end of the line, `master` prefers to select the next line all the way to the next quote instead of going left in the current line. `improve-quotes` fixes that case so I'm pleased with my limited experience with it.

**Comment by wellle** [comment]
Closed by #153.
