### ISSUE TITLE
do not screw up jump list

### ISSUE THREAD

**Issue by Konfekt** [wellle/targets.vim#138]
Let
```
Guten "Tag"!
```
with the cursor on `G`. Then after the user types
```
m`fayi"``
```
the cursor on `a`. 

Expected (= Vanilla Vim behavior): The cursor is on `G`.

Usecase: For example, sometimes it is convenient to paste text from somewhere else on the current line. Then typically `m'`, moving to the text, yanking, say by `yi"`, and returning by `''` is convenient to type and does not override marks.

**Comment by Konfekt** [comment]
How about the following remappings that leave the jump list unchanged:
```vim
nnoremap <SID>(v) v
for d in g:delimiters
  execute 'onoremap <silent> <expr> i' . d . ' ' . ''':execute "keepjumps normal \<SID>(v)'' . v:count1 . ''i' . d .'"<CR>'''
  execute 'onoremap <silent> <expr> a' . d . ' ' . ''':execute "keepjumps normal \<SID>(v)'' . v:count1 . ''a' . d .'"<CR>'''
endfor
```

**Comment by wellle** [comment]
@Konfekt: Thanks for reminding me, there's already an open pull request #132 I wanted to get back at. I'll look into it.

**Comment by Konfekt** [comment]
Exactly, that's the same problem. Would be very convenient if targets.vim could take care of it.
