### ISSUE TITLE
`i(` motion doesn't use the inner parenthesis when having multiline

### ISSUE THREAD

**Issue by netei** [wellle/targets.vim#142]
With the following file (Cursor is on `[]`)

```
r.foo().then(fun[]ction  { 
});
```

with the following `.vimrc`

```
set nocompatible

call plug#begin()                 
Plug 'wellle/targets.vim'         

call plug#end()
```

When hitting `di(` I would expect to target the current parentheses, which is`fun[]ction  { 
}` , but instead, the first parenthesis is targeted (`foo()`)

This doesn't happen without targets.vim

**Comment by wellle** [comment]
@netei: Please check if this works for you: https://github.com/wellle/targets.vim/issues/167#issuecomment-275908576

**Comment by wellle** [comment]
I'm closing this as I'm sure it can be avoided by customizing the seek ranges setting as explained in the linked comment. Please reopen if that not good enough. Thanks!
