### ISSUE TITLE
`da,` for argument trigger does not work

### ISSUE THREAD

**Issue by Ram-Z** [wellle/targets.vim#145]
With the following options:
```vim
let g:targets_separators = ',c . ; : + - = ~ _ * # / | \ & $'
let g:targets_argTrigger = ','
```

`da,` does not operate on the first or last argument.

**Comment by Sibicoder** [comment]
This mapping can help you to delete text within ,
:nmap da, f,df, 
(Works even without this plugin)

**Comment by Ram-Z** [comment]
That doesn't work in this situation either:

```cpp
void foo(int x, int y);
//          ^ cursor here
```

**Comment by wellle** [comment]
@Ram-Z: Thanks for bringing this up. :+1:

And sorry for taking so long to release a fix for this. With #152 it should be possible to use `da,`.
