### ISSUE TITLE
Trouble getting plugin to work

### ISSUE THREAD

**Issue by ColinKennedy** [wellle/targets.vim#151]
First off, let me say that I'm impressed by the level of depth this plug-in apparently has gone into to improve the way Vim manipulates wrapped text. But I say apparently though because I can't get it for the life of me to work. 

I've tried removing my entire vimrc and just running targets.vim through Vundle, I've tried that and adding/removing the default values listed in the documentation. I saw a passing mention of tpope's surround in the docs but adding/excluding it did nothing extra that his plugin didn't already do. I've also tried using targets.vim on both Windows and Linux - no dice.

I first thought that the plugin was exiting early but I use Vim 7.4 and can confirm that the whole .vim executes all the way through. That said, I couldn't even do the simplest of the examples on the doc page, like 'da,' which was supposed to leave a ',' behind when deleting between a comma-separated list.

How can I test to make sure this is loading properly?

**Comment by ColinKennedy** [comment]
Apologies, looks like part of my vimrc had this bugger in it that I forgot that I added

`for char in [ '_', '.', ':', ',', ';', '<bar>', '/', '<bslash>', '*', '+', '%', '`' ]
    execute 'xnoremap i' . char . ' :<C-u>normal! T' . char . 'vt' . char . '<CR>'
    execute 'onoremap i' . char . ' :normal vi' . char . '<CR>'
    execute 'xnoremap a' . char . ' :<C-u>normal! F' . char . 'vf' . char . '<CR>'
     execute 'onoremap a' . char . ' :normal va' . char . '<CR>'
endfor`

Removing it caused my issues to stop. Closing the issue

**Comment by wellle** [comment]
Hey @ColinKennedy, I'm glad you got it worked out! And thanks for the kind words :+1:
