### ISSUE TITLE
q to match any quote

### ISSUE THREAD

**Issue by jeromedalbert** [wellle/targets.vim#154]
This issue is similar to https://github.com/wellle/targets.vim/issues/131 but only focuses on quotes.

Before learning about this plugin, I was using [kurkale6ka/vim-pairs](https://github.com/kurkale6ka/vim-pairs). One of its features was the ability to use `ciq`, `caq` etc to match **any** kind of quote:  `'`, `"` and ```.

Having the same feature in targets.vim would be very convenient!

**Comment by wellle** [comment]
Yeah that's a great idea and I wanted to try that before. I'll look into it.

**Comment by emugel** [comment]
Would love to see that.
