### ISSUE TITLE
Confusing default behavior for arguments and parenthesis

### ISSUE THREAD

**Issue by balta2ar** [wellle/targets.vim#158]
Hello. 
### Case 1

Consider this code:

``` python
def count_fruits(apple,
                 banana, orange, lime,
                 lemon, pineapple):
```

If my cursor is on orange, lime or pineapple and I press `cia`, I change the corresponding and expected argument. However, if I put my cursor on banana, `cia` will change orange, and if I put the cursor on lemon, `cia` will change pineapple. This is rather surprising...
### Case 2

Consider this code:

``` python
self.assertEqual(datetime(),
                 compare(date|time(),
                         start, end, 'monthly'))
```

When the cursor is on the second `datetime` (second line), I could not find a combination that would change "inside parenthesis" of `compare`. 
- `ci(` and `cin(` changes inside the args of the second `datetime`
- `cil(` and `2cil(` changes inside the args of the first `datetime`
- `2ci(` changes inside the args of `assertEqual`

Again, it was surprising that I can change inside of `assertEqual`, but I can't inside of `compare`. Maybe I'm missing something? I'm using default options, no additional configuration for these cases.

Thanks!

**Comment by balta2ar** [comment]
On one hand, it looks like #142 may be related, on the other hand, recent changes to the default behavior may have rendered it outdated.

**Comment by wellle** [comment]
@balta2ar: Please check if this works for you: https://github.com/wellle/targets.vim/issues/167#issuecomment-275908576

**Comment by balta2ar** [comment]
Thank you! Suggested configuration makes targets behave more intuitively to me! I'm closing the issue.
