### ISSUE TITLE
paste in target

### ISSUE THREAD

**Issue by emugel** [wellle/targets.vim#159]
Not an issue, but more of a question. 

First of all thanks for targets.vim, it's so convenient...
...so convenient that I'd miss also being able to use for targeted pastes !

A close feature would be vim-easyclip substitution operator (overriding the 's' key by default). Unfortunately I do not want to use it because it is bloated with features and I disagree with its paradigm (send everything to the blackhole register by default seems wrong).

Do you have some workarounds to suggest?

**Comment by dbmrq** [comment]
Good idea. I just did this:

```vim
function! TargetPaste(type, ...)
    if a:type == 'line'
        normal! `[V`]p
    else
        normal! `[v`]p
    endif
endfunction

nnoremap <leader>t :set opfunc=TargetPaste<CR>g@
```

So I can do something like `<leader>tin)` to paste text replacing what's in the next parentheses.

**Comment by emugel** [comment]
Wow, thank you, this is going to be one of my favorite vim plugins!
I added a line so this can be repeated with ".", because pasting in visual mode will lose the current _""_ (so we get it back from _@0_.
```
        normal! `[v`]p
        let @" = @0         " <- I suggest to add this for repeat
```

Ah but there is just one issue, it seems to have to do with empty visual text objects, so if I _<Leader>pinb_  and it must paste into an empty _()_ it won't work.

There seem to be a discussion here https://github.com/wellle/targets.vim/issues/1 but I'm not sure if a solution was found.

**Comment by dbmrq** [comment]
Good call. I updated my comment.
As for the empty parentheses, isn't it easier to just do `f(p`?

**Comment by emugel** [comment]
Thank you.
For that a simple case, yes, but I can see a lot of use cases:
- next pair is on another line,
- jumping 2 pairs before or after (<A-p>2ilb)
- repeat paste with .
Targets works with d, y, c, so it seems almost natural to a have a paste.

Also I use Alt-p for the mapping, so A-p inb is not that much slower to type than f(p.
