### ISSUE TITLE
I have a more awesome idea for motion more quickly.

### ISSUE THREAD

**Issue by z1003031335** [wellle/targets.vim#161]
Very often there is following case:
   _, ok ^(cursor here) := (s).(string)
now i need to modify content of the second bracket,namely (string),
there are several reasons i think the mapping need to be modified.
First,in above situation,in general,what i can see is to execute f(;ci( that is not intuitive and hard to press.
Second,the same as above example,but this time i  want to modify content of the first bracket,we will execute ci( instead of cin(
From the above example,we can draw the conclusion that the mapping should be modified temporarily if it is the above situation.

**Comment by wellle** [comment]
@z1003031335: I don't follow. In your example you can type `c2in(` to change in the second next block (`string`). To change in the first next block (`s`) type `cin(` or just `ci(` because seeking will pick that one.

**Comment by z1003031335** [comment]
Ok,thinks for your quick response,this plugin is really helpful to me,i will dig into it.
