### ISSUE TITLE
"Around Separator" behavior

### ISSUE THREAD

**Issue by dbmrq** [wellle/targets.vim#162]
The "Around Separator" mappings include both separators and one white space, which makes sense when there are white spaces both before and after the separators, like in your example:

```
a , b , cccccccc , d , e
      └─── A, ────┘
```

In that case `dA,` would result in `a , b d , e`.

It doesn't make sense when there is only one white space, though, like this:

```
a, b, cccccccc, d, e
    └─── A, ───┘
```

In which case `dA,` results in `a, bd, e`.

This problem is particularly bad when writing prose. Take, for instance, something like this:

```
Take, for instance, something like this
    └──────A,──────┘
```

I would expect `dA,` to result in `Take something like this`, but it gives me  `Takesomething like this`.

Ideally the mapping would select the extra white space only when there are white spaces before _and_ after the separator… if that's not possible, it would already be helpful if there were an option to change that behavior. Something like `let g:targets_includeSpace = 0`. Then I could add that to my `ftplugin/tex.vim` and it would change the behavior for tex files, where I often run into that problem.

**Comment by wellle** [comment]
@dbmrq: That makes sense. I prepared some changes on branch [`162-separator-expand`](https://github.com/wellle/targets.vim/compare/162-separator-expand).

Could you try that version and confirm that this is the behavior you had in mind? Thank you!

**Comment by dbmrq** [comment]
Thank you! I'm on a trip right now, so it'll be a couple of weeks until I can test it, I'll report back then.

**Comment by dbmrq** [comment]
Hey, I'm sorry it took me so long to look into this. I just checked it out and it seems perfect to me. Thank you!

**Comment by wellle** [comment]
@dbmrq: Sorry for taking so long, but I finally just merged that branch and deleted it. So you might want to switch back to master now. Thanks again!

**Comment by dbmrq** [comment]
No problem, thank you! 🍾
