### ISSUE TITLE
Discrepancy between targets and vanilla vim while handling multiple quotes on a line

### ISSUE THREAD

**Issue by kshenoy** [wellle/targets.vim#168]
Let's say I  have a sentence like this with multiple quotes where `|` denotes the position of the cursor.

    The quick "brown fox " jumps |over " the lazy" dog.

In vanilla vim, if I press `da"`, I get the following:

    The quick "brown fox the lazy" dog.

while if I have targets installed without any other plugin, I get
    
    The quick "brown fox " jumps over  dog.

**Comment by wellle** [comment]
@kshenoy: Thanks for stopping by! The behavior you're seeing is intended. I changed the way how quote text objects work in https://github.com/wellle/targets.vim/pull/153. There are a few comments about the discrepancy you describe, but I havent seen a real use case where you'd really want the vanilla behavior. So if you found one, please let me know!

**Comment by kshenoy** [comment]
Sure, here's an example of how I stumbled upon it. This is a C++ cout statement on multiple lines which I was combining into a single line.

    cout << "This is a really long sentence which is split over " <<|
    "multiple lines instead of being on a single line" << endl;

The cursor is again indicated by `|` and to combine the sentences, I tried doing `Jda"`. This would've worked in vanilla vim but doesn't with targets. While intelligent seeking is a nice feature, it'd be nice if there was an option to disable it when not required.

**Comment by wellle** [comment]
Thank you for your example!

Would you prefer a global setting to disable that seeking in this case completely, or rather a different mapping that you could use to not skip in certain cases like this?

**Comment by kshenoy** [comment]
Hmm, I think I'd prefer a global setting to enable/disable intelligent seeking since I can accomplish the same using next/last.

**Comment by wellle** [comment]
Yeah that's my feeling too. Thanks for the input!

**Comment by kshenoy** [comment]
Would it be possible to make the global intelligent seeking toggle option work for not just quotes but for all types of brackets as well? 

Please let me know if you want and example or you want me to file a separate bug for this. Thanks :)

**Comment by tpict** [comment]
I've run into the same problem when joining strings over multiple lines and found myself wishing I could opt out of intelligent seeking for just that operation.

**Comment by wellle** [comment]
Ah btw, I already added a setting which you can use to tweak the quote directions and seeking options. For your use case, try putting these lines into your vimrc/init.vim:
```vim
let g:targets_quoteDirs = {
            \ 'r1n': ['001', '201', '100', '102'],
            \ 'r1l': ['010', '012', '111', '210', '212'],
            \ 'r2n': ['101'],
            \ 'r2l': ['011', '211'],
            \ 'r2b': ['000', '002', '200', '202'],
            \ 'l2r': ['110', '112'],
            \ }
```
That way you can select the current quote even if it is "false", but it's still smart (`v2anq` still skips the false ones).

It's currently undocumented and I might change how this can be customised later, but for now this should work.
