### ISSUE TITLE
Edge case of VimL comments fails

### ISSUE THREAD

**Issue by lifecrisis** [wellle/targets.vim#177]
When operating on a block of VimL like the following,

```VimL
" ============================================================================
" SECTION: "The Section Title"
" ============================================================================
```

positioning the cursor on, say, `Title` and executing the macro `ci"` results in unexpected behavior. Specifically, the innards of the first set of quotes are deleted and `Insert` mode is entered there.

Just reporting an edge case that needs to be addressed.

**Comment by wellle** [comment]
Sorry for the late response. I'm actually working on some changes related to quote text objects which should fix this case. The basic idea is to avoid trying to be smart about selecting quotes if there's an odd number of quotation characters in the current line, as seen here.

**Comment by wellle** [comment]
Should be fixed, please try again.

**Comment by lifecrisis** [comment]
Hi, @wellle, I gave it a shot, and it works!  Thanks for fixing this edge case!
