### ISSUE TITLE
add support for curly braces in arguments

### ISSUE THREAD

**Issue by acornejo** [wellle/targets.vim#182]
This is particularly useful for dealing with dictionaries in languages such as python, ruby, etc.

```
{ key1: val1, key2: val2, key3: val3 }
```

I would want daa to work. Interestingly since it supports square braces then it works in the following:

```
[ key1: val1, key2: val2, key3: val3 ]
```
Therefore this already supports swift ;)

**Comment by acornejo** [comment]
Ohh, I should add that I have also run into this issue when using initializer lists in C++.

i.e.

```
 std::string s1{'a', 'b', 'c', 'd'}
```

**Comment by wellle** [comment]
@acornejo: It's already supported, but not enabled by default. Check the docs: https://github.com/wellle/targets.vim#gtargets_argopening-and-gtargets_argclosing

**Comment by acornejo** [comment]
Yup, just found it:

```
let g:targets_argOpening = '[({[]'
let g:targets_argClosing = '[]})]'
```

I would suggest making this the default. Closing this. Btw, much thanks for the amazing plugin.

**Comment by wellle** [comment]
Thank you! I might consider that. There's also #130.

**Comment by 0xC0FFEE** [comment]
I just ran into this too, while trying to make the argument textobject work with C++ 'uniform initialization'.

Since C++11 curly braces can be used to initialize arbitrary objects e.g. `int i{2}`. I'd second to me this the default behavior. But I'm not sure whether this will have any unwanted side effects.

Unrelated, but not less important: thank you so much for this awesome plugin! IMHO it perfectly fits the 'vim way' of doing things. It feels so natural to me, that this (at least some parts of the plugin) should be considered to be core vim/neovim functionality.

**Comment by wellle** [comment]
@0xC0FFEE: Thanks for your comment and thanks for your kind words!

Yes, the usage of `targets#mappings#extend` looks good and is the recommended way to include curly braces for arguments. 👍 

My concern about adding curly braces to the default comes from cases like this:
```go
func foo(x int) string {
	// ...

	z = x+1 // cursor in this line
	bar(y, z)

	// ...
}
```
With the cursor on the `z =` line, with current default settings I can `cia` to seek into the next line to change `y`. If curly braces are included, then `cia` will actually change the full inner function body, as it looks like a big argument (in curly braces) to targets.vim. And I do find it very disorienting when that happens, so I'm kind of hesitant to include it and potentially confuse new users in such cases. Does that make sense?

**Comment by 0xC0FFEE** [comment]
Ah I see. Actually it makes perfect sense to me. The great thing is however, that this option can be customized, so people can configure it depending on their needs :+1:.

With the above in mind, I think leaving the defaults as is, should be good for most people and it avoids confusion. Thanks for clarifying!
