### ISSUE TITLE
Test suite fails for selection=exclusive

### ISSUE THREAD

**Issue by nkgm** [wellle/targets.vim#184]
I've been experimenting with `set selection=exclusive` for some time now. Brushing up on my `targets` I noticed a discrepancy between `vi{` and `vib`. Turns out test suite fails in various ways for this option. Not even sure if `exclusive` is such a good idea in the first place, so I'm just throwing it out there hoping to get your thoughts on this.

**Comment by wellle** [comment]
@nkgm: The `'selection'` option is supposed to be properly handled since `v0.2.3`. Can you give me an example where `vi{` behaves differently than `vib`? I tried both selection inclusive and exclusive with both vanilla Vim and with targets.vim, and it all seems consistent to me.

**Comment by nkgm** [comment]
@wellle [here](https://github.com/wellle/targets.vim/compare/master...nkgm:nkgm-%23184?expand=1) is where it fails for me. Would you also consider incorporating `--no-pager` as demonstrated, to make it a bit more environment independent?

**Comment by wellle** [comment]
I think I can reproduce it, it's in test4, right? I'll check that 👍 

Good idea with the `--no-pager` flag, in the meantime I already started to put the diffs in files. So it now only shows what failed and you'll have to cat the diff separately (I with I could still have it colored though). Do you think that's alright?

**Comment by nkgm** [comment]
Yes it's test4.

> Do you think that's alright?

l think the present form is fine, but I guess your improvements will keep clutter under control if (god forbid) multiple tests fail in a run.

On a relevant topic, I believe the test suite is nothing short of ingenious in that you used common household items to build a smart bomb. With the ongoing conversation about edge cases, I've been thinking of easy ways to capture them and test them. It's quite often that I hit an edge case while in the middle of a project, but it's too much hassle to keep track of them as they arise. I'm thinking the notation you use on the cheatsheet could serve as some sort of executable documentation. That would be really beneficial for the more complex cases, and, should you decide to leverage `syntax` where available, could enable inlining the specs as comments in regular source files. At the risk of getting ahead of myself, what do you think?

**Comment by wellle** [comment]
@nkgm: I fixed a bug that the tests revealed for selection=exclusive, thanks for bringing it up 👍 

And thanks for the kind words, yes I tried to keep it low tech. I saw some vimscript testing frameworks pop up over the time, and I think some of them look pretty cool, like [vader.vim](https://github.com/junegunn/vader.vim).

But I'm not sure if it makes sense to migrate the current tests over to something more readable. Lets just look at test1. The input file is 28 line, the vimscript function is 84 lines, and the way how it tests lost of combinations by nesting some loops, this generates over 4400 output lines. So with a more conventional approach I'm assuming this would be something like thousands of very very similar tests. In a way that I would probably need to generate them somehow automatically, at which point I don't thinks that's very useful anymore. Nobody is going to wade through thousand of these test setups anyway.

For regressions, where I add smaller tests for specific bugs we've seen, this might be a better opportunity. But at the same time I'm not sure how I feel about using different test approaches for different tests.

But I do understand your position and agree that it would be useful to have documentation and tests come closer together. I'll keep that in mind and give it some more thought. Thank you for your feedback. 👍

**Comment by nkgm** [comment]
@wellle thanks for fixing this.

> But I'm not sure if it makes sense to migrate the current tests over to something more readable. Lets just look at test1.

I was certainly not suggesting rewriting the existing (brute-force as I affectionately call it) test suite as it perfectly serves its purpose. 

> For regressions, where I add smaller tests for specific bugs we've seen, this might be a better opportunity.

My idea as well. It would also make more sense should you ever need to test `syntax` aware features in their natural `filetype`s.
