### ISSUE TITLE
Undefined variable rl

### ISSUE THREAD

**Issue by vimeitor** [wellle/targets.vim#189]
Cursor over either of the closing parentheses. Typing 2cia throws an error.
```
foo(bar, baz(a, b, c))
```
You can actually simplify this to
```
foo(bar, baz)
```
and calling 2cia from the closing parentheses as well.

I don't think it's too big of a deal; it certainly doesn't affect me, but I will put it here anyway just in case you want to fix this :-)

Thank you for your work on this plugin. It's probably the highest quality plugin I've ever seen. Superb customizability and documentation, and very clean code.

**Comment by wellle** [comment]
Thank you, I can reproduce the issue and will look into it 👍

**Comment by wellle** [comment]
Should be fixed, thanks again!

**Comment by vimeitor** [comment]
Thank you!
