### ISSUE TITLE
Default operator map 'iw' doesnt work after last update

### ISSUE THREAD

**Issue by romgrk** [wellle/targets.vim#204]
I ran `:PlugUpdate` sooner today and the default `iw` stopped working. The only output of `omap iw` is target.vim's `i` mapping.

I ran a git bisect to find the commit which started this regression and it is this one:

```
0972bd73a7f612d50fb9335bfd623a89fea4eb43 is the first bad commit
commit 0972bd73a7f612d50fb9335bfd623a89fea4eb43
Author: Christian Wellenbrock <christian.wellenbrock@gmail.com>
Date:   Sun Dec 3 12:55:15 2017 +0100

    Prefer expression mappings for operator-pending mode
    
    If possible only create a few expression mappings. Otherwise fall back
    to create many individual mappings.

:040000 040000 c76b9875aa9a4f58da9823cc3dfcc2886ecf0e90 449f23f817fdb2f31ffc8262b70695acc6f4fff1 M	autoload
:040000 040000 63d56e077c9002378ca6509971b89209e09dbeac eca9bb631c9c9538cb3882338c431ca6c5aa9ace M	plugin
```

Let me know if you need more details. I'm running late for a meeting but I'll post more details later today.

**Comment by wellle** [comment]
Oh, interesting. Can you show me your `vim --version` output?
Also can you give me a full example containing of buffer contents, cursor position and exactly what keys you're typing?
And after you tried using `iw`, can you run `:messages` in the same vim session and show me the output of that, if any?

Hope you had a good meeting!

**Comment by wellle** [comment]
Actually, since you managed to bisect it, you could enable some additional logging before trying again (not sure if that's going to be useful, but maybe worth a shot, will show up in `:messages`), by activating this line by removing the `"`: https://github.com/wellle/targets.vim/blob/d722c2c6b306f77c1720e5dc77fab39b542579dc/autoload/targets.vim#L1289

**Comment by romgrk** [comment]
Ok, so the problem is that the line here is returning `'Iw'` when I do `'iw'`.

https://github.com/wellle/targets.vim/blob/d722c2c6b306f77c1720e5dc77fab39b542579dc/autoload/targets.vim#L130-L133

The reason it does that is because my configuration contains:
```vim
let targets_aiAI = 'aIAi'
```

I'll open a PR with a fix in a moment.
