### ISSUE TITLE
g:targets_aiAI modifies visual mode mappings

### ISSUE THREAD

**Issue by matthsims** [wellle/targets.vim#211]
Normally in visual block mode, `I` goes to the front of the block and starts an insert. When I define `let g:targets_aiAI = 'aIAi'`, and start visual-block mode, `I` now does nothing, and `i` quickly followed by another character starts the insert as `I` should.

The documentation for that setting doesn't say anything about xmode mappings.

**Comment by wellle** [comment]
@matthsims: Thank you! I fixed it in #212. Can you try again?

**Comment by matthsims** [comment]
Works perfectly, thanks!
