### ISSUE TITLE
Making a mapping for @

### ISSUE THREAD

**Issue by ColinKennedy** [wellle/targets.vim#226]
I have text that uses @ to wrap paths like how " is used to path strings. (e.g. "foo" 'foo' \`foo\`). For my purposes, I want @ to be treated exactly as if it were wrapping a path, like @/usr/local@

I tried to extend targets.vim to do this but it didn't work. This is what I tried:

```
autocmd User targets#mappings#user call targets#mappings#extend({
    \ '\@': {'quote': [{'d': '@'}]},
    \ })
```

I noticed in the README that "@" was used to be "anything" so I thought to try different combinations with escaped \\@ and without \ but nothing worked. Any help would be appreciated

**Comment by wellle** [comment]
Hey!

The part about `@` in the readme is only an example of how to extend the mappings. By default it is not mapped to anything at all.

You already got it right. You don't need to escape in there. I put this into my vimrc and it worked.
```vim
autocmd User targets#mappings#user call targets#mappings#extend({
            \ '@': {'quote': [{'d': '@'}]},
            \ })
```

For example if I have `@/usr/local@` in my buffer and type `di@` then it leaves `@@`. Please let me know if that doesn't work for you.

**Comment by ColinKennedy** [comment]
The code you posted works for me. Thank you! I'll close this ticket now
