### ISSUE TITLE
[RFC] Be gracious about too large counts

### ISSUE THREAD

**Issue by kiryph** [wellle/targets.vim#229]
Currently, targets.vim is in agreement with the builtin behaviour of text objects regarding too large counts by treating this like there is no corresponding text object:

[Stolen example from wellle:](https://github.com/lervag/vimtex/pull/1384#issuecomment-493054063)
> ```
> a ( b ) ( c ) ( ( x ) ) ( e ) ( f ) g
> ```
> put your cursor on the x. Now if you type vib it selects the inner block, if instead you type v2ib it selects in the outer block, but if instead you type v3ib or any bigger number, then nothing will be selected. Similarly try dib, d2ib and d3ib.

Other implementations of text objects, e.g. vimtex's version of ic/ac/ie/ae for LaTeX commands and LaTeX environments are "gracious" and simply would treat v3ib like v2ib or any larger number in the above given example.

I like the "gracious" behaviour which allows the user to select the most outer object without really counting by simply providing a too large number (9 or 99).

Are there good reasons why people would prefer the builtin behaviour?

**Comment by wellle** [comment]
@kiryph: I added a global setting for this in #230. Please give it a shot and let me know if it works as you expected.

**Comment by kiryph** [comment]
I gave it shot. Yes, it works for me. Thank you!

Now I will see whether I can modify the PR for vimtex. It would be nice if the setting `g:targets_gracious` is also respected by the targets.vim variants of vimtex's text objects.
