### ISSUE TITLE
Typo in readme example?

### ISSUE THREAD

**Issue by Chiel92** [wellle/targets.vim#236]
In de Readme it says:

> To change the text in the next pair of parentheses, use the `cin)` command

However, executing that does nothing to my buffer. Executing `ci)` instead seems to have the desired effect. Is this a typo?

**Comment by wellle** [comment]
Nope, doesn't look like a typo to me. What you might be experiencing is seeking. When the cursor is not within parentheses, `ci)` will seek into a nearby pair. But `cin)` should always change in the next pair (which is not surrounding the cursor). Try it on this line with the cursor on `x`:
```
a ( x ) b ( c )
```
If you type `ci)` it should replace the `x`. If you do `cin)` instead it should change the `c`.

**Comment by Chiel92** [comment]
My bad, you are indeed correct.
