### ISSUE TITLE
Swap i with I 

### ISSUE THREAD

**Issue by j-blasco** [wellle/targets.vim#238]
When we want to change something in a text object, isn't it the most general case that we want to keep the spaces? 

In the following text:

f ( first argument, second argument)

If I want to change the first argument, I would like to write "cia", but this deletes also the space! and I need to type "cIa" . I would see "I" as an extended version of "i", thus including the spaces, which is less usual. 

This is also the default behavior in vim, right? if I have the following:
This is a sentence. This is another <cursor> sentence.

If we type "cis" (change in sentence), we want to change the sentence, and therefore the space is not included.
 
Is it possible to customize this behavior?

**Comment by wellle** [comment]
Yes, see https://github.com/wellle/targets.vim#gtargets_aiai

In your case, try:
```vim
let g:targets_aiAI = 'aIAi'
```

**Comment by j-blasco** [comment]
Fantastic
