### ISSUE TITLE
Nested Quotes Not Matching Correctly in Prose

### ISSUE THREAD

**Issue by oncomouse** [wellle/targets.vim#259]
I'm working with some incorrectly nested quotes in a piece of writing (trying to switch `"` to `'`) and I'm finding that the textobj for quotes does not work as expected (nor as it works in Neovim without targets). For instance:

With targets (cursor at `.`):

~~~
"aaa "b.bb" ccc"
          |_a"_|
~~~

But without targets:

~~~
"aaa "b.bb" ccc"
     |_a"_|
~~~

To my eyes (as an English professor, if that matters), the behavior without targets is correct (it selects the embedded quote).

I tried following the docs and set `g:targets_seekRanges` to "Only consider targets around cursor" (produced below):

~~~
let g:targets_seekRanges = 'cc cr cb cB lc ac Ac lr lb ar ab lB Ar aB Ab AB'
~~~

When I do that, running `a"` on my earlier example, nothing is selected.

I see why the problem is occurring (the textobj is matching the first and second quotes as one quotation and the third and the fourth as the other), but in prose, that matching order isn't correct (because of where the spaces are around the quotation marks).

If I was matching dialogue in a book, like:

> "Vim is awesome," she said, "if difficult."

And I ran `a"` anywhere in `" she said, "` I would expect vim to grab `"if difficult"` because `" she said, "` has spaces after the first quotation mark and before the last.

But if I'm working with incorrectly punctuated nested quotes (which I am (it's student writing)), where I have something like:

> "When the author says "vim is easy!" I am suspicious"

If my cursor is anywhere inside `"vim is easy!"` I want to grab that with `a"` because there is not a space after the first quote nor before the last.

I realize there are situations where I'm programming and I would want `"aaa "bbb" ccc"` to match the way it does currently in targets (like string concatenation, for instance: `"Hello, "+name.first+" "+name.last`), but it's frustrating that it doesn't work correctly for prose punctuation. Also, because this selection rule seems baked into the textobj, I can't see a way to turn it off (I thought setting `g:targets_seekRanges` would fix this, but it doesn't appear to).

Is there any setting I could use to make this behave properly for prose? Or is there a way to turn off all the quotation targets only in specific `filetype` buffers?

**Comment by wellle** [comment]
Hey! Yes this is working as intended. Most of the times these "false" quotes are not one wants to operate on. So the decision was made in #153 to seek to the next quote in that case. It does lead to a few edge cases like the one you describe here. There have been similar issues like this in the past. For example please refer to this https://github.com/wellle/targets.vim/issues/168#issuecomment-450574560 for a suggestion of how to change this behavior for you. Please let me know if that helps.
