### ISSUE TITLE
Unable to select pair text object with other pair on the same line

### ISSUE THREAD

**Issue by Fymyte** [wellle/targets.vim#276]
Hi, after playing quite a lot with this (amazing) plugin, I found myself unable to select the surrounding block with the cursor anywhere on the points
```lua
table = {
  query_linter = {
    enable = true,
    use_virtual_text = true,
.................
    lint_event = {"BufWrite", "CursorHold"},
  }
}
```
`vi}` will select the content of `lint_event` (`"BufWrite", "CursorHold"`) which is expected, but `v2i}` will select the content of `table` instead of `query_linter`, so I am unable to select the content of `query_linter` for line 5.
That's not a big deal but is there a workaround ?

**Comment by wellle** [comment]
Hey! Yes the default behavior prefers the contents of lint_events here and I don't think it's possible to select the contents of query_linter here from there. You could change the seeking behavior to prefer bigger targets around the cursor over smaller targets within the cursor line with
```vim
let g:targets_seekRanges = 'cc cr cb cB lc ac Ac lr lb ar ab lB Ar aB Ab AB rr ll rb al rB Al bb aa bB Aa BB AA'
```
See https://github.com/wellle/targets.vim#gtargets_seekranges.
