### ISSUE TITLE
Non-intuitive behavior with line seeking in certain edge cases.

### ISSUE THREAD

**Issue by thang1thang2** [wellle/targets.vim#83]
I noticed this first in my .vimrc because I have some fun bindings in there and apparently they make the plugin act funny... Minimal working example here, X being cursor position.

```
let g = {
     \ { arg 1 },
    X\ { arg 2 },
}
```

If you type the command `ci{`, the resulting output should (intuitively) erase "arg 2" and leave you in the appropriate spot in insert mode. The current behavior ends up with 

```
let g = {
X
}
```

However `cin{` works fine, and `cil{` performs on the curly braces surrounding "arg 1" as expected.

The second bug is similar.

```
X beautifulCode text [ things ] ; 
...
(50 lines down the vimrc later)
...
noremap p ]p
```

Typing `ci[` from the cursor position erases EVERYTHING in-between the first bracket and the one at the last line, leaving the result:

```
beautifulCode text [X]p
```

Typing `cin[` works properly, however. Additionally, it's also worth noting that vim's built in % matching command seems to automatically match the first line with the "matching" bracket 50 lines down, just like your plugin does.

It seems to me that, intuitively, the plugin should automatically seek within the line first, and then +/-1, before going to the "largest area currently within". However, that does raise the question of how you would operate on the entire surrounding curly brace (e.g. in example 1) if the plugin defaulted to line search, so perhaps a proximity setting might be in order? If I'm within, say, 10-15 characters of something more narrow that matches the command, then act on that instead of the wider selection, and if I'm further away from it (say, at the other end of a line of code), the plugin should act on the larger area.

An example:

```
let g = {
    [X]more text, and other fancy things, probablyLongEnoughToBeAJava[Y]NameNow { arg },
}
```

If the cursor was at, say, the position of [X], then `ci{` would act on the curly braces surrounding the entire line, whereas if it was at the position [Y], `ci{` would act on the braces surrounding "arg".

One last issue. If I have some text like:

```
X  ..... 
(30 lines down)
<foo> things
```

And I press `ci<`, the cursor will jump all 30 lines down and give the result `<X>`. This is cool, but I don't know if having the text searching being unlimited is really a good idea, I imagine it would be horribly frustrating to hit the wrong key and accidentally end up somewhere 200 lines over, in a larger codebase. Perhaps a vertical limit of, say, ~15 lines would be more appropriate? Of course this and the line-wise priority could be adjustable/able to be turned off by the end user, or whatever.

Sorry for the wall of text. Also not quite sure whether to call this a bug or "thang1thang2 is weird and likes weird things and makes weird suggestions"...

**Comment by wellle** [comment]
@thang1thang2: Sorry for the late update, but seeking has been improved and made customizable in #129. I just tested your example again and it works now as you desired. Thanks!
